config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  get 'about', to: 'about#show'

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
    resources :sales, only: [:index, :new]
  end
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy' 

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def show
    @products_count = Product.all.count
    @categories_count = Category.all.count
  end
end

app/views/admin/dashboard/show.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; Dashboard</h1>
  </header>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
        <%# colspan="2" %>
          <th >Category</th>
          <th>Number</th>
          <th>Link</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <h4>Products</h4>
          </td>
          <td>
            <p><%= @products_count%></p>
          </td>
          <td>
            <%= link_to 'Products Admin Page', admin_products_path, class: 'btn btn-sm btn-primary' %>
          </td>
        </tr>
        <tr>
          <td>
            <h4>Categories</h4>
          </td>
          <td>
            <p><%= @categories_count%></p>
          </td>
          <td>
            <%= link_to 'Categories Admin Page', admin_categories_path, class: 'btn btn-sm btn-primary' %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

</section>